name: Docker Image CI

on:
  push:
    branches: [ CmstNewVersion2 ]
  pull_request:
    branches: [ CmstNewVersion2 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: check out code
      uses: actions/checkout@v2

    - 
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  

    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: supermalang/digitalcms-webapp:$(date +%s)

    #- uses 
    #  run: docker build . --file Dockerfile --tag supermalang/digitalcms-webapp:$(date +%s) --tag supermalang/digitalcms-webapp:latest
